blog/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token

from blog_app import view_set
router = DefaultRouter()
router.register(r'users', view_set.UserViewSet)
router.register(r'posts', view_set.PostViewSet)
router.register(r'comentarios', view_set.ComentarioViewSet)
router.register(r'categorias',view_set.CategoriaViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)), 
    path('api/token/', obtain_auth_token, name='api_token'), 
    path('', include('blog_app.urls')), 
    path('', include('user.urls')), 
   ]

blog_app/urls.py
from django.urls import path,include
from markdownx import urls as markdownx_urls

from blog_app import views, view_set
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', views.home, name='Home'),
    path('ayuda/', views.ayuda, name='Ayuda'),
    path('blog/', views.blog, name='Blog'),
    path('categoria/<int:categoria_id>/', views.categoria, name='Categoria'),
    path('post/<int:post_id>/', views.view_post, name='Post'),
    path('my-posts/',views.my_posts,name='MyPosts'),
    path('create_post', views.create_post, name='Create_Post'),
    path('markdownx/', include(markdownx_urls)),
    path('delete-post/<int:post_id>',views.delete_post,name='deletePost'),
    path('edit-post/<int:post_id>',views.edit_post,name='editPost'),
    path('post/<int:post_id>/like/', views.like_post, name='like_post'),
    path('add-comment/',views.add_comment,name='addComment'),
    path('delete-comment/<int:comentario_id>',views.delete_comment,name='deleteComment'),
    path('search/', views.search, name='Search'),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

blog_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
 
class Categoria(models.Model):
    nombre = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now_add=True)  
    class Meta:
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.nombre 
    
class Post(models.Model):
    titulo = models.CharField(max_length=50)
    introduccion = models.CharField(max_length=100)
    contenido = models.TextField()
    imagen = models.ImageField(upload_to='post', null=True) 
    autor = models.ForeignKey(User, on_delete=models.CASCADE)  
    categoria = models.ManyToManyField(Categoria) 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now_add=True) 

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'

    def __str__(self):
        return f'{self.titulo} creado por {self.autor.username}'
   
    
class Comentario(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    contenido = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'comentario'
        verbose_name_plural = 'comentarios'

    def __str__(self):
        return f"Comentario de {self.usuario.username} en {self.post.titulo}"


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'like'
        verbose_name_plural = 'likes'

    def __str__(self):
        return f"Like de {self.usuario.username} en {self.post.titulo}"

blog_app/views.py
from django.core.paginator import Paginator
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.http import HttpResponseRedirect

from .models import Post,Categoria,Like,Comentario


# Create your views here.
def home(request):
    view_name= 'Home' 
    context = {
        "home_css":"blog_app/css/home.css",
        "slider_css":"blog_app/css/slider.css",
        "swiperBundleCss":"blog_app/css/swiper-bundle.min.css",
        #Scripts 
        "swiperBundleJs":"blog_app/js/swiper-bundle.min.js",
        "sliderJs":"blog_app/js/slider.js",
        }
    latest_posts = Post.objects.all().order_by('-created')[:5]
    return render(request, 'blog_app/home.html',{'view_name': view_name,"context":context,"latest_posts":latest_posts})

def ayuda(request):
    view_name = 'Ayuda'
    context = {
        "ayuda_css":'blog_app/css/ayuda.css'
    }
    return render(request,'blog_app/ayuda.html',{'view_name':view_name,'context':context})

def blog (request):
    view_name='Blog'
    context = {
        "blog_css":"blog_app/css/blog.css",
        "pagination_css":"blog_app/css/pagination.css",
    }
    
    posts = Post.objects.all().order_by('-created')
    paginator = Paginator(posts,12)
    page = request.GET.get('pagina')
    page_object = paginator.get_page(page)
    
    return render(request,'blog_app/blog.html',{'view_name':view_name,'context':context,'posts':posts,'page_object':page_object})

def categoria(request,categoria_id):
    view_name='Categoria'
    context = {
        "blog_css":"blog_app/css/blog.css",
        "categoria_css":"blog_app/css/categoria.css",
    }
    
    categoria = Categoria.objects.get(id=categoria_id)
    posts = Post.objects.filter(categoria=categoria).order_by('-created')
    return render(request,'blog_app/filtro_categoria.html',{'view_name':view_name,'context':context,'categoria':categoria,'posts':posts})


#View one post 
def view_post(request, post_id): 
    view_name = 'View_post'
    context = {
        "post_css":"blog_app/css/post.css",
        "post_js":"blog_app/js/post.js",
        
        }
    post = Post.objects.get(id=post_id)
    return render(request, 'blog_app/post.html', {'view_name':view_name,"context":context ,'post': post})



# View My posts
@login_required
def my_posts(request):
    view_name = 'Mis Posts'
    context = {
        "userPosts": "blog_app/css/user_posts.css",
    }

    user = request.user
    posts = Post.objects.filter(autor=user).order_by('-created')
    paginator = Paginator(posts, 12)
    page = request.GET.get('pagina')
    page_object = paginator.get_page(page)

    return render(request, 'blog_app/user_posts.html', {
        'view_name': view_name,
        'context': context,
        'posts': posts,
        'page_object': page_object
    })
  
  
## Create Post
def create_post(request):
    view_name = 'Create_Post'
    context = {
        "css_file": "blog_app/css/create_post.css",
    }
    categorias = Categoria.objects.all()
    
    if request.method == 'POST':
        titulo = request.POST.get('titulo')
        introduccion = request.POST.get('introduccion')
        categoria_id = request.POST.get('categoria')
        contenido = request.POST.get('contenido')
        categoria_id = request.POST.get('categoria')
        categoria = Categoria.objects.get(id=categoria_id)
        imagen = request.FILES.get('imagen')
        autor = request.user

        if imagen and imagen.size > settings.MAX_UPLOAD_SIZE:
            error_message = 'La imagen es demasiado grande. El tamaño máximo permitido es de 5 MB.'
            return render(request, 'blog_app/create_post.html', {
                'view_name': view_name,
                'context': context,
                'categorias': categorias,
                'error_message': error_message,
                'titulo': titulo,
                'categoria_id': int(categoria_id),
                'contenido': contenido
            })
        else:
            post = Post(titulo=titulo,introduccion=introduccion, contenido=contenido, imagen=imagen, autor=autor)
            post.save()
            post.categoria.set([categoria])
            return redirect('Blog')

    return render(request, 'blog_app/create_post.html', {
        'view_name': view_name,
        'context': context,
        'categorias': categorias
    })
    
## Delete post
@login_required
def delete_post(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()
    return redirect('MyPosts') 
   
   
# Edit Post
@login_required
def edit_post(request, post_id):
    post = Post.objects.get(id=post_id)
    
    view_name = 'Edit_Post'
    context = {
        "css_file": "blog_app/css/create_post.css",
    }
    categorias = Categoria.objects.all()

    if request.method == 'POST':
        post.titulo = request.POST.get('titulo', post.titulo)
        post.introduccion = request.POST.get('introduccion', post.introduccion)
        post.contenido = request.POST.get('contenido', post.contenido)
        
        categoria_id = request.POST.get('categoria')
        if categoria_id:
            categoria = Categoria.objects.get(id=categoria_id)
            post.categoria.set([categoria])

        imagen = request.FILES.get('imagen')
        if imagen and imagen.size > settings.MAX_UPLOAD_SIZE:
            error_message = 'La imagen es demasiado grande. El tamaño máximo permitido es de 5 MB.'
            return render(request, 'blog_app/edit_post.html', {
                'view_name': view_name,
                'context': context,
                'post': post,
                'categorias': categorias,
                'error_message': error_message
            })
        elif imagen:
            post.imagen = imagen

        post.save()
        return redirect('MyPosts')

    return render(request, 'blog_app/edit_post.html', {
        'view_name': view_name,
        'context': context,
        'post': post,
        'categorias': categorias
    })

@login_required
def like_post(request, post_id):
    post = Post.objects.get(id=post_id)
    user = request.user

    like_exists = Like.objects.filter(post=post, usuario=user).exists()

    if like_exists:
        Like.objects.filter(post=post, usuario=user).delete()
    else:
        Like.objects.create(post=post, usuario=user)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def add_comment(request):
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post = Post.objects.get(id=post_id)
        comentario = request.POST.get('newComment')
        usuario = request.user
        Comentario.objects.create(post=post, usuario=usuario, contenido=comentario)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def delete_comment(request, comentario_id):
    comentario = Comentario.objects.get(id=comentario_id)
    comentario.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


# Barra de busqueda 
def search(request):
    view_name = 'Search'
    context = {
        "css_file":"blog_app/css/blog.css",
        "search_css":"blog_app/css/search.css",
        
        
        }
    query = request.GET.get('search')
    results = Post.objects.filter(titulo__icontains=query) |  Post.objects.filter(introduccion__icontains=query) | Post.objects.filter(contenido__icontains=query)
    return render(request, 'blog_app/search.html', {
        'view_name':view_name,
        'context':context, 
        'results': results, 
        })

blog_app/templates/blog_app/ayuda.html
{% extends './base.html' %} <!-- hereda de la plantilla base.html-->

{% load static %}

{% block css_file %}
    {{ block.super }} 
    <link href="{% static context.ayuda_css %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="markdown-help">
        <h1>Guía de Markdown</h1>
        <p>Markdown es una sintaxis de marcado simple que te permite formatear el texto de una manera más fácil y rápida. Aquí tienes algunos ejemplos de cómo puedes usar Markdown:</p>
        
        <h2>Encabezados</h2>
        <pre>
# Encabezado de nivel 1
## Encabezado de nivel 2
### Encabezado de nivel 3
        </pre>
        
        <h2>Negrita e Itálica</h2>
        <pre>
**Texto en negrita**
*Texto en itálica*
        </pre>
        
        <h2>Listas</h2>
        <pre>
- Elemento de lista 1
- Elemento de lista 2
- Elemento de lista 3
        </pre>
        
        <h2>Listas Numeradas</h2>
        <pre>
1. Elemento 1
2. Elemento 2
3. Elemento 3
        </pre>
        
        <h2>Enlaces</h2>
        <pre>
[Texto del enlace](URL_del_enlace)
        </pre>
        <h2>Imágenes</h2>
        <pre>
![Texto alternativo](URL_de_la_imagen)
        </pre>
        
        <h2>Código en línea y Bloques de código</h2>
        <pre>
`Código en línea`

</pre>
        
<h2>Citas</h2>
<pre>
> Esto es una cita.
</pre>

<h2>Línea horizontal</h2>
<pre>
---
</pre>

<p>Recuerda que puedes utilizar Markdown en tus posts para darles un formato más elegante y legible.</p>
</div>
{% endblock %}

blog_app/templates/blog_app/base.html
{% load static %}
<html>
  <head>
    <!-- Base -->
    <link href="{% static 'blog_app/css/side_bar.css' %}" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'blog_app/css/base.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% block css_file %}{% endblock %}

    {% block title %}
    {% endblock %}
  </head>

  <body>
    {% include 'blog_app/widgets/side_bar_menu.html' %}
       
 
       
       
        

    <!-- Contentido cambiante  -->
    {% block content %}
    {% endblock %}

     




     
      {% block script_file %}{% endblock %}
      <script src="{% static 'blog_app/js/side_bar_script.js' %}"></script>
      {% block javascript %}
        <script>
          const viewName = "{{ view_name }}";
        </script>
      {% endblock %}


  </body>


</html>

blog_app/templates/blog_app/blog.html
{% extends './base.html' %} <!-- hereda de la plantilla base.html-->

{% load static %}

{% block css_file %}
    {{ block.super }} 
    <link href="{% static context.blog_css %}" rel="stylesheet">
    <link href="{% static context.pagination_css %}" rel="stylesheet">
    <!-- <link href="{% static context.swiperBundleCss %}" rel="stylesheet"> -->

{% endblock %}

{% block content %}
<div id="indexBlog">
    <div id="postsContainer">
        {% for post in page_object %}
            <div id="containerPost">
                <div id="headerPost">
                    <span id="autorPost">{{ post.autor }}</span>
                    <span id="likesPost"><a href="{% url 'like_post' post.id %}">{{ post.like_set.count }}<i class='bx bxs-like'></i></a></span>
            <span id="commentsPost"><a href="#">{{ post.comentario_set.count }}</a><i class='bx bx-comment'></i></span>
            
                    <img src="{{ post.imagen.url }}" alt="{{ post.titulo }}" class="card_img">
                </div>
                <div id="bodyPost">
                    <a href="{% url 'Post' post.id %}" ><h2 id="titlePost">{{ post.titulo|truncatechars:30 }}</h2></a>
                    <p id="contentPost">{{ post.introduccion }}</p>
                </div>
                <div id="footerPost">
                    <div id="categoriaContainer" >
                        {% for categorias in post.categoria.all|slice:":3" %}
                        <a href="{% url 'Categoria' categorias.id %}" ><span id="categoria">{{ categorias.nombre }}</span></a>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        
        <div class="pagination">
        {% if page_object.has_previous %}
        <a href="?pagina={{ page_object.previous_page_number }}">anterior</a>
        {% endif %}
        
        <span class="current-page">{{ page_object.number }}</span>
        
        {% if page_object.has_next %}
            <a href="?pagina={{ page_object.next_page_number }}">siguiente</a>
        {% endif %}
    </div>
</div>

{% endblock %}

blog_app/templates/blog_app/create_post.html
{% extends '../blog_app/base.html' %}

{% load static %}
{% block css_file %}
{{ block.super }}
<link href="{% static context.css_file %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="containerForm">
    <h1 id="user_title">Bienvenido <strong>{{ user.username }}</strong></h1>
    <p id="create_post">Aquí puedes crear tu Post</p>
    
    <form method="POST" action="{% url 'Create_Post' %}"  enctype="multipart/form-data"> 
        {% csrf_token %} 
        <div class="titulo">
            <h3>Título</h3>
            <input type="text" name="titulo" class="form-control" id="inputTitle" placeholder="Título del post..." value="{{ titulo }}" maxlength="50" required>
        </div>
        <div class="intro">
            <input type="text" name="introduccion" class="form-control" id="inputIntro" placeholder="Introducción..." value="{{ introduccion }}" maxlength="100" required>
        </div>
        <div class="drop_img">
            <div class="dropdown">
                <select name="categoria" required>
                    <option value="">Categoría del Post...</option>
                    {% for categoria in categorias %}
                        {% if categoria.id == categoria_id %}
                            <option value="{{ categoria.id }}" selected>{{ categoria.nombre }}</option>
                        {% else %}
                            <option value="{{ categoria.id }}">{{ categoria.nombre }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="inputImage">
                <input name="imagen" type="file" accept="image/*" max="5242880" enctype="multipart/form-data" class="form-control" id="inputImage" required>
                <span>- La imagen no debe superar los <strong>5 MB</strong>.</span>
                {% if error_message %}
                    <p class="error-message">{{ error_message }}</p>
                {% endif %}
            </div>
        </div>
        <div class="contenido">
            <textarea class="form-control" name="contenido" id="exampleFormControlTextarea1" rows="3" placeholder="Escribe aquí el contenido de tu posteo en formato Markdown..." required>{{ contenido }}</textarea>
            <span style="color:gray;font-style:italic">Si tienes dudas sobre cómo usar el formato Markdown, haz <a href="{% url 'Ayuda' %}" style="text-decoration: none;color:orange;">clic aquí</a></span>
        </div>
        
        <div class="button">
            <input type="submit" value="Crear Post"/>
        </div>
    </form>
    
</div>
{% endblock %}

blog_app/templates/blog_app/edit_post.html
{% extends '../blog_app/base.html' %}

{% load static %}
{% block css_file %}
{{ block.super }}
<link href="{% static context.css_file %}" rel="stylesheet">

{% endblock %}
{% block content %}

<div class="containerForm">

    <h1 id= "user_title" > Bienvenido <strong>{{user.username}}</strong></h1>
    <p id="create_post" > Aquí puedes editar tu Post</p>
    
        <form method="POST" enctype="multipart/form-data"> 
            {% csrf_token %} 
            <div class="titulo">
                <h3>Título</h3>
                <input type="text" name="titulo" class="form-control" id="inputTitle" placeholder="{{ post.titulo }}" value="{{ post.titulo }}"maxlength="50">
            </div>
            <div class="intro">
                <input type="text" name="introduccion" class="form-control" id="inputIntro" placeholder="{{ post.introduccion }}"" value="{{ post.introduccion }}"maxlength="100">
            </div>
            <div class="drop_img">
                <div class="dropdown">
                    <select name="categoria">
                        <option>Categoría del Post...</option>
                        {% for categoria in categorias %}
                            {% if categoria.id == post.categoria.id %}
                                <option value="{{ categoria.id }}" selected>{{ categoria.nombre }}</option>
                            {% else %}
                                <option value="{{ categoria.id }}">{{ categoria.nombre }}</option>
                            {% endif %}
                    {% endfor %}
                    </select>
                </div>
                <div class="inputImage">
                    <input name="imagen" type="file" accept="image/*" max="5242880" enctype="multipart/form-data" class="form-control" id="inputImage">
                    
                    <span>- La imágen no debe superar los <strong>5 MB</strong>.</span>
                    {% if error_message %}
                        <p class="error-message" >{{ error_message }}</p>
                    {% endif %}
                </div>
            </div>
            <div class="contenido">
                <textarea class="form-control" name="contenido" id="exampleFormControlTextarea1" rows="3" placeholder="{{ post.contenido }}" >{{ post.contenido }}</textarea>
                <span style="color:gray;font-style:italic"> Si tienes dudas sobre como usar el formato Markdown haz <a href="{% url 'Ayuda' %}" style="text-decoration: none;color:orange;">aquí</a></span>
            </div>
            
            <div class="button">
                <input type="submit" value="Guardar edición"/>
            </div>
        </form>
        
        
</div>
{% endblock %}

blog_app/templates/blog_app/filtro_categoria.html
{% extends './base.html' %} <!-- hereda de la plantilla base.html-->

{% load static %}

{% block css_file %}
    {{ block.super }} 
    <link href="{% static context.blog_css %}" rel="stylesheet">
    <link href="{% static context.categoria_css %}" rel="stylesheet">
{% endblock %}


{% block content %}
<div id="indexCategorias">
    <div class="glitch-wrapper">
        <div class="glitch" data-text="{{categoria.nombre}}">{{categoria.nombre}}</div>
    </div>
    
    <div id="postsContainer">
        {% for post in posts %}
        <div id="containerPost">
            <div id="headerPost">
                <span id="autorPost">{{ post.autor }}</span>
                <span id="likesPost"><a href="{% url 'like_post' post.id %}">{{ post.like_set.count }}<i class='bx bxs-like'></i></a></span>
                <span id="commentsPost"><a href="#">{{ post.comentario_set.count }}</a><i class='bx bxs-comment'></i></span>
                <img src="{{ post.imagen.url }}" alt="{{ post.titulo }}" class="card_img">
            </div>
            <div id="bodyPost">
                <a href="{% url 'Post' post.id %}" ><h2 id="titlePost">{{ post.titulo|truncatechars:30 }}</h2></a>
                <p id="contentPost">{{ post.contenido|truncatechars:100 }}</p>
            </div>
            <div id="footerPost">
                <div id="categoriaContainer" >
                    {% for categorias in post.categoria.all|slice:":3" %}
                    <a href="{% url 'Categoria' categorias.id %}" ><span id="categoria">{{ categorias.nombre }}</span></a>
                    {% endfor %}
                        </div>
                    </div>
                </div>
          
                {% endfor %}
            </div>
            
</div>

{% endblock %}

blog_app/templates/blog_app/home.html
{% extends './base.html' %} <!-- hereda de la plantilla base.html-->

{% load static %}

{% block css_file %}
    {{ block.super }} 
    <link href="{% static context.home_css %}" rel="stylesheet">
    <link href="{% static context.slider_css %}" rel="stylesheet">
    <link href="{% static context.swiperBundleCss %}" rel="stylesheet">

{% endblock %}



{% block content %}

    <!-- Carrousel -->
    
    <div id="homeContainer" >
        <div class="slide-container swiper">
            <div class="glitch-wrapper">
                <div class="glitch" data-text="Últimos posteos">Últimos posteos</div>
             </div>
          <div class="slide-content">
              <div class="card-wrapper swiper-wrapper">
               
              {% for post in latest_posts %}
                <div class="card swiper-slide" id="cardPost">
                    <div id="headerPost">
                            <img src="{{ post.imagen.url }}" alt="{{ post.titulo }}" class="card_img" >
                    </div>
                    <div id="contentPost">
                        <a href="{% url 'Post' post.id %}"class='viewpost'><h2 id="titlePost">{{ post.titulo|truncatechars:30}}</h2></a>
                        <p id="descriptionPost">{{ post.introduccion }}</p>
                    </div>
                    
                </div>
                  {% endfor %}
              </div>
          </div>
          <div class="glitch-wrapper" id="categoriaTitle">
            <div class="glitch" data-text="Categorías">Categorías</div>
        </div>
        <div id="contextCategorias">
            {% for categoria in categorias %}
            <a id="categoria" href="{% url 'Categoria' categoria.id %}">{{ categoria.nombre }}</a>
            {% endfor %}
        </div>
         </div>




    </div>

    

    
    {% block script_file %}
    {{ block.super }}
    <script src="{% static context.swiperBundleJs %}"></script>
    <script src="{% static context.sliderJs %}"></script>

    {% endblock %}

     

{% endblock %}

blog_app/templates/blog_app/post.html
{% extends '../blog_app/base.html' %} <!-- hereda de la plantilla base.html-->
{% load markdown_extras %}

{% load static %}

{% block css_file %}
{{ block.super }}
    <link href="{% static context.post_css %}" rel="stylesheet">
{% endblock %}

{% block content %}

      
    <!-- Ver posteo completo -->
    <div id="bigContainer">

        <div id="indexPost">
            <div id="headerPost">
                <span id="likesPost"><a href="{% url 'like_post' post.id %}">{{ post.like_set.count }}<i class='bx bxs-like'></i></a></span>
                <span id="commentsPost"><a href="#">{{ post.comentario_set.count }}</a><i class='bx bxs-comment'></i></span>
                <img src="{{ post.imagen.url }}" alt="{{ post.titulo }}">
            </div>
        <div id="bodyPost">
            <div id="headerBody">
                <h3>{{post.titulo}}</h3>
                <span>Creado por {{post.autor}} - {{ post.created|date:"d M Y" }}</span>
            </div>
            <div id="contentBody" class="markdown-content">
                <p>{{ post.contenido|markdown|safe}}</p>
            </div>
        </div>
        <div id="footerPost">
            <span>Última actualización {{ post.updated|date:"d M Y" }}</span>
        </div>
        
    </div>
    <div id="indexComentarios"> 
        <h2>Comentarios </h2>
        <div id="comentarioContainer">

            {% for comentario in comentarios %}
            {% if post.id == comentario.post.id %}
            <div class="comentario">
                <div class="card-body"> 
                    <h3>{{ comentario.usuario }}</h3>
                    <p>{{ comentario.contenido }}</p>
                    <span>{{ comentario.created }}</span>
                    {% if user == comentario.usuario %}
                    <a id="deleteComment" href="{% url 'deleteComment' comentario.id %}"><i class='bx bxs-trash-alt'></i></a>
                    {% endif %}
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <div id="formComentario">

            <!-- {% if user.is_authenticated %} -->
            <form method="POST" id="formComment" action="{% url 'addComment' %}"> 
                {% csrf_token %} 
                <input type="hidden" name="post_id" value="{{ post.id }}">
                
                <input type="text" name="newComment" class="form-control" id="inputIntro" placeholder="Escribe un comentario..."  maxlength="200" required>
                <input type="submit" value="Comentar"/>
            </form>
        </div>
            <!-- {% endif %} -->
    </div>
    
    
    </div>
    <div id="scrollButton">&#8593;</div>
   
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var comentariosSpan = document.getElementById('commentsPost');
            var comentariosDiv = document.getElementById('Comentarios');
        
            comentariosSpan.addEventListener('click', function() {
                comentariosDiv.scrollIntoView({ behavior: 'smooth' });
            });
        });
    </script>        

    {% block script_file %}
        {{ block.super }}
        <script src="{% static context.post_js %}"></script>

    {% endblock %}


{% endblock %}

blog_app/templates/blog_app/search.html
{% extends './base.html' %} <!-- hereda de la plantilla base.html-->

{% load static %}

{% block css_file %}
    {{ block.super }} 
    <link href="{% static context.css_file %}" rel="stylesheet">
    <link href="{% static context.search_css %}" rel="stylesheet">
{% endblock %}


{% block content %}
{% if results %}
    <div id="indexSearch">
        <div class="glitch-wrapper">
            <div class="glitch" data-text="Resultado de busqueda">Resultado de busqueda</div>
        </div>
        
        <div id="postsContainer">
            {% for post in results %}
            <div id="containerPost">
                <div id="headerPost">
                    <span id="autorPost">{{ post.autor }}</span>
                    <span id="likesPost"><a href="{% url 'like_post' post.id %}">{{ post.like_set.count }}<i class='bx bxs-like'></i></a></span>
                    <span id="commentsPost"><a href="#">{{ post.comentario_set.count }}</a><i class='bx bxs-comment'></i></span>
                    <img src="{{ post.imagen.url }}" alt="{{ post.titulo }}" class="card_img">
                </div>
                <div id="bodyPost">
                    <a href="{% url 'Post' post.id %}" ><h2 id="titlePost">{{ post.titulo|truncatechars:30 }}</h2></a>
                    <p id="contentPost">{{ post.contenido|truncatechars:100 }}</p>
                </div>
                <div id="footerPost">
                    <div id="categoriaContainer" >
                        {% for categorias in post.categoria.all|slice:":3" %}
                        <a href="{% url 'Categoria' categorias.id %}" ><span id="categoria">{{ categorias.nombre }}</span></a>
                        {% endfor %}
                            </div>
                        </div>
                    </div>
            
                    {% endfor %}
                </div>
                
    </div>
{% else %}
    <div id="indexSearch">
        {% include 'blog_app/widgets/no_result.html' %}
    </div>
{% endif %}  
 
{% endblock %}